



/*Süreç CIID bazýnda Silinmiþ ama eksik tablodan silinmiþ. Active Actions Kaydý Duruyor */
SELECT * FROM INST_ACTIVE_ACTIONS WHERE CIID NOT IN (SELECT CIID FROM INST_COURSE)

/*Görev Formun Hatalý Bir þekilde INST_ACTIVE_ACTIONS tablosuna yazýlmýþ */
SELECT CIID,DESCRIPTION FROM INST_ACTIVE_ACTIONS IAA WITH(NOLOCK) 
INNER JOIN TMPL_ACT_MASTER TAM WITH(NOLOCK) ON (IAA.AID=TAM.AID)
AND TASKTYPE = 1

/*Süreç Açýk, Görev Formu yok ve Þu anda Devam Etmiyor*/
select * from INST_COURSE WHERE CIID NOT IN (SELECT CIID FROM INST_TASKS)
AND COMPLETED IS NULL

/*Alt Süreç varken Süreç Silinmiþ. Ýzleri duruyor*/
select * from SYS_SUB_STACK WHERE CALLING_CIID NOT IN (SELECT CIID FROM INST_COURSE)

SELECT * FROM SYS_SUB_STACK WHERE RETURN_CIID NOT IN (SELECT CIID FROM INST_COURSE)

/*SYS_LOG kaydý mevcut süreç silinmiþ*/
SELECT * FROM SYS_LOG WHERE CIID NOT IN (SELECT CIID FROM INST_COURSE)
AND CIID!=0

/*INST_ACTIVE_ACTIONS kayýt var fakat ilgili bileþen süreçten silinmiþ*/
SELECT * FROM INST_ACTIVE_ACTIONS WHERE AID NOT IN (SELECT AID FROM TMPL_ACT_MASTER)

/*Çoklayan Görev Formlarýný Silme Sorgusu */

DECLARE
@TABLE TABLE(TIID INT,AID INT,CIID INT)
DECLARE
@TIID INT,
@AID INT,
@CIID INT

/*5327*/

INSERT INTO @TABLE
SELECT MAX(TIID),AID,CIID FROM INST_TASKS WHERE CAST(CIID AS nvarchar)+'-'+CAST( AID AS nvarchar) IN (
SELECT CAST(CIID AS nvarchar)+'-'+CAST( AID AS nvarchar) FROM INST_TASKS
GROUP BY CIID,AID
HAVING COUNT(*)>1)
GROUP BY AID,CIID


DECLARE
V_CURSOR CURSOR FOR 
SELECT * FROM @TABLE

OPEN V_CURSOR
FETCH NEXT FROM V_CURSOR INTO @TIID,@AID,@CIID

WHILE
@@FETCH_STATUS = 0
BEGIN

DELETE FROM INST_TASKS WHERE CIID = @CIID AND AID = @AID AND TIID!=@TIID

FETCH NEXT FROM V_CURSOR INTO @TIID,@AID,@CIID

END

CLOSE V_CURSOR
DEALLOCATE V_CURSOR

